name: Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - '3.1.4'

    steps:
    - uses: actions/checkout@v3
    - name: Find Chrome
      run: |
        whereis chrome
        whereis chromium
        whereis google-chrome
        whereis chromedriver

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Unit tests
      run: bin/rspec
